pipeline{
    agent any

    tools{
        maven 'Maven 3.6.1'

    }

    stages{
        stage('build'){
            steps{
                echo "Building worker app"
                dir(‘worker'){
                    sh 'mvn compile'
                }
                sleep 5
            }
        }
        stage('test'){
            steps{
                echo "Running tests on the build"
                sleep 3
            }
        }
        stage('package'){
            steps{
                echo "Packagingg..."
                sleep 1
            }
        }
    }
    post{
        always{
            echo "Told hi to Jeevan, Ajay and Madhuri"
        }
    }
}